struct JSONKey {
    static let id                           = "id"
    static let name                         = "name"
    static let username                     = "username"
    static let password                     = "password"
    static let firstName                    = "first_name"
    static let lastName                     = "last_name"
    static let gender                       = "gender"
    static let email                        = "email"
    static let refreshToken                 = "access_token"
    static let accessToken                  = "access_token"
    static let clientId                     = "client_id"
    static let clientSecret                 = "client_secret"
    static let grantType                    = "grant_type"
    static let applicationState             = "application_state"
    static let aps                          = "aps"
    static let customer                       = "customer"
}
